(cl:defpackage robot_communication-msg
  (:use )
  (:export
   "<APRILTAGDETECTION>"
   "APRILTAGDETECTION"
   "<APRILTAGDETECTIONARRAY>"
   "APRILTAGDETECTIONARRAY"
   "<SCHEDULERCOMMAND>"
   "SCHEDULERCOMMAND"
   "<SCHEDULERRESPONSE>"
   "SCHEDULERRESPONSE"
   "<ENCODER_COMM>"
   "ENCODER_COMM"
   "<ULTRASONIC_COMM>"
   "ULTRASONIC_COMM"
   "<VELOCITY_COMM>"
   "VELOCITY_COMM"
  ))

