# ~/.bashrc

# Se não estiver rodando interativamente, saia
case $- in
    *i*) ;;
      *) return;;
esac

# Histórico
HISTCONTROL=ignoreboth
shopt -s histappend
HISTSIZE=1000
HISTFILESIZE=2000

# Ajusta o terminal ao redimensionar
shopt -s checkwinsize

# Aliases (se existir)
if [ -f ~/.bash_aliases ]; then
    . ~/.bash_aliases
fi
i
# Configurando ROS 1 Noetic
ROS_SETUP_BASH="/opt/ros/noetic/setup.bash"

if [ -f "$ROS_SETUP_BASH" ]; then
    source "$ROS_SETUP_BASH"
else
    echo "[.bashrc] AVISO: setup.bash do ROS não encontrado em $ROS_SETUP_BASH"
fi

# Bash completion
if ! shopt -oq posix; then
  if [ -f /usr/share/bash-completion/bash_completion ]; then
    . /usr/share/bash-completion/bash_completion
  elif [ -f /etc/bash_completion ]; then
    . /etc/bash_completion
  fi
fi

# Source do ambiente do container
source ~/Shared/Work_2026/robot_ws/devel/setup.bash