<?xml version="1.0"?>
<package format="2">
  <name>robot_vision</name>
  <version>0.0.0</version>
  <description>Package para o sistema de visão com detecção AprilTag.</description>

  <maintainer email="rmajetson@todo.todo">rmajetson</maintainer>
  <license>TODO</license>

  <buildtool_depend>catkin</buildtool_depend>

  <build_depend>rospy</build_depend>
  <build_depend>std_msgs</build_depend>
  <build_depend>sensor_msgs</build_depend>
  <build_depend>cv_bridge</build_depend> <exec_depend>rospy</exec_depend>
  <exec_depend>std_msgs</exec_depend>
  <exec_depend>sensor_msgs</exec_depend>
  <exec_depend>cv_bridge</exec_depend>
  <depend>robot_communication</depend>
  
  <export>
  </export>
</package>