services:
  ros_noetic:
    # --- Identificação do Container ---
    container_name: ${CNAME}
    
    # --- Definição da Imagem ---
    image: ${INAME}:${TAG}
    
    # Configurações de construção da imagem (Build)
    build:
      # Pasta onde está o Dockerfile
      context: ${DPATH}
      dockerfile: Dockerfile
      # Argumentos passados para o Dockerfile durante o build
      args:
        USER_UID: ${USER_UID}
        USER_GID: ${USER_GID}
        USERNAME: ${DOCKER_USER}

    # --- Configurações de Rede e IPC ---
    # 'host': Remove o isolamento de rede. O container compartilha o IP do host.
    network_mode: host
    
    # Compartilha a memória com o host. Necessário para GUIs (X11) e performance
    ipc: host

    # --- Mapeamento de Volumes e Dispositivos ---
    volumes:
      # Permite que aplicações gráficas (Rviz, Gazebo) usem o servidor X11 do host
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      
      # Mapeia a pasta /dev inteira para acesso a hardware (USB, Serial, Câmeras)
      - /dev:/dev
      
      # Volume persistente: Mapeia sua pasta local de desenvolvimento para dentro do container
      - ${DPATH}/share:/home/${DOCKER_USER}/Shared

    # --- Regras de Permissão de Hardware ---
    # Permite acesso dinâmico a dispositivos
    device_cgroup_rules:
      - 'c *:* rmw'

    # --- Variáveis de Ambiente ---
    environment:
      # Encaminha o display do host para o container
      - DISPLAY=${DISPLAY}
      # Correção para bibliotecas Qt/GUI no Docker
      - QT_X11_NO_MITSHM=1
      # Garante suporte a cores no terminal
      - TERM=xterm-256color 

    # --- Configurações de Execução ---
    # Define o usuário que rodará os processos
    user: ${DOCKER_USER}
    
    # Pasta inicial ao abrir o terminal
    working_dir: /home/${DOCKER_USER}
    
    # Mantém o container rodando indefinidamente
    command: zsh
    
    # Aloca um TTY e mantém o STDIN aberto (necessário para modo interativo)
    stdin_open: true
    tty: true