standalone_tags:
  [
    {id: 1, size: 0.030, name: "tag1"},
    {id: 2, size: 0.030, name: "tag2"},
    {id: 3, size: 0.030, name: "tag3"},
    {id: 4, size: 0.030, name: "tag4"},
    {id: 5, size: 0.030, name: "tag5"},
    {id: 6, size: 0.030, name: "tag6"},
    {id: 7, size: 0.030, name: "tag7"},
    {id: 8, size: 0.030, name: "tag8"},
    {id: 9, size: 0.030, name: "tag9"},
    {id: 10, size: 0.030, name: "tag10"},
    {id: 11, size: 0.030, name: "tag11"},
    {id: 12, size: 0.030, name: "tag12"},
    {id: 13, size: 0.030, name: "tag13"},
    {id: 14, size: 0.030, name: "tag14"},
    {id: 15, size: 0.030, name: "tag15"},
    {id: 16, size: 0.030, name: "tag16"},
    {id: 17, size: 0.030, name: "tag17"},
    {id: 18, size: 0.030, name: "tag18"},
    {id: 19, size: 0.030, name: "tag19"},
    {id: 20, size: 0.030, name: "tag20"},
    {id: 21, size: 0.030, name: "tag21"},
    {id: 22, size: 0.030, name: "tag22"},
    {id: 23, size: 0.030, name: "tag23"},
    {id: 24, size: 0.030, name: "tag24"},
    {id: 25, size: 0.030, name: "tag25"},
    {id: 26, size: 0.030, name: "tag26"},
    {id: 27, size: 0.030, name: "tag27"}
  ]

tag_bundles:
  [
  ]
