// Generated by gencpp from file robot_communication/SchedulerResponse.msg
// DO NOT EDIT!


#ifndef ROBOT_COMMUNICATION_MESSAGE_SCHEDULERRESPONSE_H
#define ROBOT_COMMUNICATION_MESSAGE_SCHEDULERRESPONSE_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_communication
{
template <class ContainerAllocator>
struct SchedulerResponse_
{
  typedef SchedulerResponse_<ContainerAllocator> Type;

  SchedulerResponse_()
    : uid(0)
    , target()
    , status()  {
    }
  SchedulerResponse_(const ContainerAllocator& _alloc)
    : uid(0)
    , target(_alloc)
    , status(_alloc)  {
  (void)_alloc;
    }



   typedef uint64_t _uid_type;
  _uid_type uid;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _target_type;
  _target_type target;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _status_type;
  _status_type status;





  typedef boost::shared_ptr< ::robot_communication::SchedulerResponse_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_communication::SchedulerResponse_<ContainerAllocator> const> ConstPtr;

}; // struct SchedulerResponse_

typedef ::robot_communication::SchedulerResponse_<std::allocator<void> > SchedulerResponse;

typedef boost::shared_ptr< ::robot_communication::SchedulerResponse > SchedulerResponsePtr;
typedef boost::shared_ptr< ::robot_communication::SchedulerResponse const> SchedulerResponseConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_communication::SchedulerResponse_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_communication::SchedulerResponse_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_communication::SchedulerResponse_<ContainerAllocator1> & lhs, const ::robot_communication::SchedulerResponse_<ContainerAllocator2> & rhs)
{
  return lhs.uid == rhs.uid &&
    lhs.target == rhs.target &&
    lhs.status == rhs.status;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_communication::SchedulerResponse_<ContainerAllocator1> & lhs, const ::robot_communication::SchedulerResponse_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_communication

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_communication::SchedulerResponse_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_communication::SchedulerResponse_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_communication::SchedulerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_communication::SchedulerResponse_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_communication::SchedulerResponse_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_communication::SchedulerResponse_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_communication::SchedulerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "e762c6baa6b0e70c2b053bc0f5604848";
  }

  static const char* value(const ::robot_communication::SchedulerResponse_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xe762c6baa6b0e70cULL;
  static const uint64_t static_value2 = 0x2b053bc0f5604848ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_communication::SchedulerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_communication/SchedulerResponse";
  }

  static const char* value(const ::robot_communication::SchedulerResponse_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_communication::SchedulerResponse_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# SchedulerResponse.msg\n"
"uint64 uid\n"
"string target\n"
"string status\n"
;
  }

  static const char* value(const ::robot_communication::SchedulerResponse_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_communication::SchedulerResponse_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.uid);
      stream.next(m.target);
      stream.next(m.status);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SchedulerResponse_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_communication::SchedulerResponse_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_communication::SchedulerResponse_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "uid: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.uid);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "target: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.target);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "status: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.status);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_COMMUNICATION_MESSAGE_SCHEDULERRESPONSE_H
