// Generated by gencpp from file robot_communication/SchedulerCommand.msg
// DO NOT EDIT!


#ifndef ROBOT_COMMUNICATION_MESSAGE_SCHEDULERCOMMAND_H
#define ROBOT_COMMUNICATION_MESSAGE_SCHEDULERCOMMAND_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_communication
{
template <class ContainerAllocator>
struct SchedulerCommand_
{
  typedef SchedulerCommand_<ContainerAllocator> Type;

  SchedulerCommand_()
    : uid(0)
    , target()
    , payload()
    , need_ack(false)
    , timeout(0.0)  {
    }
  SchedulerCommand_(const ContainerAllocator& _alloc)
    : uid(0)
    , target(_alloc)
    , payload(_alloc)
    , need_ack(false)
    , timeout(0.0)  {
  (void)_alloc;
    }



   typedef uint64_t _uid_type;
  _uid_type uid;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _target_type;
  _target_type target;

   typedef std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>> _payload_type;
  _payload_type payload;

   typedef uint8_t _need_ack_type;
  _need_ack_type need_ack;

   typedef float _timeout_type;
  _timeout_type timeout;





  typedef boost::shared_ptr< ::robot_communication::SchedulerCommand_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_communication::SchedulerCommand_<ContainerAllocator> const> ConstPtr;

}; // struct SchedulerCommand_

typedef ::robot_communication::SchedulerCommand_<std::allocator<void> > SchedulerCommand;

typedef boost::shared_ptr< ::robot_communication::SchedulerCommand > SchedulerCommandPtr;
typedef boost::shared_ptr< ::robot_communication::SchedulerCommand const> SchedulerCommandConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_communication::SchedulerCommand_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_communication::SchedulerCommand_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_communication::SchedulerCommand_<ContainerAllocator1> & lhs, const ::robot_communication::SchedulerCommand_<ContainerAllocator2> & rhs)
{
  return lhs.uid == rhs.uid &&
    lhs.target == rhs.target &&
    lhs.payload == rhs.payload &&
    lhs.need_ack == rhs.need_ack &&
    lhs.timeout == rhs.timeout;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_communication::SchedulerCommand_<ContainerAllocator1> & lhs, const ::robot_communication::SchedulerCommand_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_communication

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_communication::SchedulerCommand_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_communication::SchedulerCommand_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_communication::SchedulerCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_communication::SchedulerCommand_<ContainerAllocator> const>
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_communication::SchedulerCommand_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_communication::SchedulerCommand_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_communication::SchedulerCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "95112fe84583f15f46a9728e120c0c3a";
  }

  static const char* value(const ::robot_communication::SchedulerCommand_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x95112fe84583f15fULL;
  static const uint64_t static_value2 = 0x46a9728e120c0c3aULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_communication::SchedulerCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_communication/SchedulerCommand";
  }

  static const char* value(const ::robot_communication::SchedulerCommand_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_communication::SchedulerCommand_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# SchedulerCommand.msg\n"
"uint64 uid\n"
"string target\n"
"string payload\n"
"bool need_ack\n"
"float32 timeout\n"
;
  }

  static const char* value(const ::robot_communication::SchedulerCommand_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_communication::SchedulerCommand_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.uid);
      stream.next(m.target);
      stream.next(m.payload);
      stream.next(m.need_ack);
      stream.next(m.timeout);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct SchedulerCommand_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_communication::SchedulerCommand_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_communication::SchedulerCommand_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "uid: ";
    Printer<uint64_t>::stream(s, indent + "  ", v.uid);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "target: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.target);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "payload: ";
    Printer<std::basic_string<char, std::char_traits<char>, typename std::allocator_traits<ContainerAllocator>::template rebind_alloc<char>>>::stream(s, indent + "  ", v.payload);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "need_ack: ";
    Printer<uint8_t>::stream(s, indent + "  ", v.need_ack);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "timeout: ";
    Printer<float>::stream(s, indent + "  ", v.timeout);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_COMMUNICATION_MESSAGE_SCHEDULERCOMMAND_H
