// Generated by gencpp from file robot_communication/ultrasonic_comm.msg
// DO NOT EDIT!


#ifndef ROBOT_COMMUNICATION_MESSAGE_ULTRASONIC_COMM_H
#define ROBOT_COMMUNICATION_MESSAGE_ULTRASONIC_COMM_H


#include <string>
#include <vector>
#include <memory>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace robot_communication
{
template <class ContainerAllocator>
struct ultrasonic_comm_
{
  typedef ultrasonic_comm_<ContainerAllocator> Type;

  ultrasonic_comm_()
    : front_left(0.0)
    , front_right(0.0)
    , rear_left(0.0)
    , rear_right(0.0)
    , back(0.0)  {
    }
  ultrasonic_comm_(const ContainerAllocator& _alloc)
    : front_left(0.0)
    , front_right(0.0)
    , rear_left(0.0)
    , rear_right(0.0)
    , back(0.0)  {
  (void)_alloc;
    }



   typedef float _front_left_type;
  _front_left_type front_left;

   typedef float _front_right_type;
  _front_right_type front_right;

   typedef float _rear_left_type;
  _rear_left_type rear_left;

   typedef float _rear_right_type;
  _rear_right_type rear_right;

   typedef float _back_type;
  _back_type back;





  typedef boost::shared_ptr< ::robot_communication::ultrasonic_comm_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::robot_communication::ultrasonic_comm_<ContainerAllocator> const> ConstPtr;

}; // struct ultrasonic_comm_

typedef ::robot_communication::ultrasonic_comm_<std::allocator<void> > ultrasonic_comm;

typedef boost::shared_ptr< ::robot_communication::ultrasonic_comm > ultrasonic_commPtr;
typedef boost::shared_ptr< ::robot_communication::ultrasonic_comm const> ultrasonic_commConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::robot_communication::ultrasonic_comm_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::robot_communication::ultrasonic_comm_<ContainerAllocator> >::stream(s, "", v);
return s;
}


template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator==(const ::robot_communication::ultrasonic_comm_<ContainerAllocator1> & lhs, const ::robot_communication::ultrasonic_comm_<ContainerAllocator2> & rhs)
{
  return lhs.front_left == rhs.front_left &&
    lhs.front_right == rhs.front_right &&
    lhs.rear_left == rhs.rear_left &&
    lhs.rear_right == rhs.rear_right &&
    lhs.back == rhs.back;
}

template<typename ContainerAllocator1, typename ContainerAllocator2>
bool operator!=(const ::robot_communication::ultrasonic_comm_<ContainerAllocator1> & lhs, const ::robot_communication::ultrasonic_comm_<ContainerAllocator2> & rhs)
{
  return !(lhs == rhs);
}


} // namespace robot_communication

namespace ros
{
namespace message_traits
{





template <class ContainerAllocator>
struct IsMessage< ::robot_communication::ultrasonic_comm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::robot_communication::ultrasonic_comm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_communication::ultrasonic_comm_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::robot_communication::ultrasonic_comm_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_communication::ultrasonic_comm_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::robot_communication::ultrasonic_comm_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::robot_communication::ultrasonic_comm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "428636691d2e367ce654d88bbe9851c3";
  }

  static const char* value(const ::robot_communication::ultrasonic_comm_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0x428636691d2e367cULL;
  static const uint64_t static_value2 = 0xe654d88bbe9851c3ULL;
};

template<class ContainerAllocator>
struct DataType< ::robot_communication::ultrasonic_comm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "robot_communication/ultrasonic_comm";
  }

  static const char* value(const ::robot_communication::ultrasonic_comm_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::robot_communication::ultrasonic_comm_<ContainerAllocator> >
{
  static const char* value()
  {
    return "# ultrasonic_comm.msg\n"
"float32 front_left\n"
"float32 front_right\n"
"float32 rear_left\n"
"float32 rear_right\n"
"float32 back\n"
;
  }

  static const char* value(const ::robot_communication::ultrasonic_comm_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::robot_communication::ultrasonic_comm_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream& stream, T m)
    {
      stream.next(m.front_left);
      stream.next(m.front_right);
      stream.next(m.rear_left);
      stream.next(m.rear_right);
      stream.next(m.back);
    }

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct ultrasonic_comm_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::robot_communication::ultrasonic_comm_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream& s, const std::string& indent, const ::robot_communication::ultrasonic_comm_<ContainerAllocator>& v)
  {
    if (false || !indent.empty())
      s << std::endl;
    s << indent << "front_left: ";
    Printer<float>::stream(s, indent + "  ", v.front_left);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "front_right: ";
    Printer<float>::stream(s, indent + "  ", v.front_right);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rear_left: ";
    Printer<float>::stream(s, indent + "  ", v.rear_left);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "rear_right: ";
    Printer<float>::stream(s, indent + "  ", v.rear_right);
    if (true || !indent.empty())
      s << std::endl;
    s << indent << "back: ";
    Printer<float>::stream(s, indent + "  ", v.back);
  }
};

} // namespace message_operations
} // namespace ros

#endif // ROBOT_COMMUNICATION_MESSAGE_ULTRASONIC_COMM_H
