odom_model_type: "omni-corrected"
odom_frame_id: "odom"
base_frame_id: "base_footprint"
global_frame_id: "map"

# Configurações de Partículas
min_particles: 500
max_particles: 2000

# Frequência de atualização
update_min_d: 0.3
update_min_a: 0.2

# Ruído da Odometria
odom_alpha1: 0.05
odom_alpha2: 0.05
odom_alpha3: 0.05
odom_alpha4: 0.05
odom_alpha5: 0.05

# Recuperação
recovery_alpha_slow: 0.0
recovery_alpha_fast: 0.0

# Correção da latência
transform_tolerance: 1.5